# Generated by Django 4.2.30 on 2026-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the tale,myth, or legend', max_length=255)),
                ('content', models.TextField(help_text='The full text of the Story here')),
                ('narrator', models.CharField(help_text='The person who told, or remembered the story', max_length=255)),
                ('audio_recording', models.FileField(blank=True, help_text='Optional voice recording of the story', null=True, upload_to='audio/stories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
