# Generated by Django 4.2.30 on 2026-07-31 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='uploader',
            field=models.ForeignKey(default=1, help_text='The user that uploaded this story', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='e.g. ,Mastuj ,Chitral', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short description about yourself/contributor')),
                ('languages', models.CharField(blank=True, help_text='e.g., Khowar, Urdu', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
