# Generated by Django 4.2.30 on 2026-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0002_story_uploader_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='region',
            field=models.CharField(default=1, help_text='The region or village this story is from (e.g., Mastuj)', max_length=100),
            preserve_default=False,
        ),
    ]
