# Generated by Django 4.2.30 on 2026-08-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0003_story_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(help_text='The name of the tale, myth, or legend', max_length=255),
        ),
    ]
